### ISSUE TITLE
Product categories are not updated but deleted and recreated with a new slug

### ISSUE THREAD

**Issue by squareloop1** [jtl-software/connector-woocommerce3#11]
We've found a new odd behavior when updating product category content:

Instead of updating already existing product categories the category gets recreated or renamed to another slug instead of just updated. So if you have e.g. an existing product category with the slug "product-category" synced earlier by JTL and you update the description text of the product category in JTL and sync it with WooCommerce it will become "product-category-2" which is breaking permalink structure.

**Comment by squareloop1** [comment]
Neither name or url path was changed and it was working fine up until one of the latest versions. Is there anything that could be done to force the connector to keep the existing product category slugs to prevent breaking permalink structure on every sync to the shop?

**Comment by paprykasz** [comment]
Category slugs shouldn't be changed in case there was no change in name or urlPath. Maybe issue is related to your other plugin? Best will be if you can contact our support and provide more info about it.
