### ISSUE TITLE
Wrong shipping costs & taxes in case of mixed tax rates

### ISSUE THREAD

**Issue by MaxBaumR1** [jtl-software/connector-woocommerce3#12]
Hi,

we updated from version 1.32.1 to 1.36.1 and noticed that the shipping costs and shipping taxes are imported wrong to JTL for all orders with mixed tax rates.
E.g. order in Germany with Food 7% Tax and Non Food 19%
After looking into the code i noticed the change in:

woo-jtl-connector/src/Controllers/Order/CustomerOrderItem.php 
$netPrice = ($costs * $factor) / count($taxes['total']);

In case of mixed tax rate (7% and 19%) the $netPrice is divided by 2 which is not correct!
After reverting the code to  $netPrice = ($costs * $factor); the results in JTL are better but still wrong.
So i assume something else was change too.

We are reverting to 1.32.1
![woo](https://user-images.githubusercontent.com/76008816/177800808-f6a3ec58-9784-4272-8c57-3b140307d454.png)
![jtl](https://user-images.githubusercontent.com/76008816/177800815-cab8a128-91dc-4c84-a3eb-bd3b8fb2297a.PNG)

**Comment by paprykasz** [comment]
Hey @MaxBaumR1,

thank you for your feedback. There was change recently in shipping split algorithm that could cause problems. We are currently working on solution for this issue. If you would like to test development version contact me via [JTL forum](https://forum.jtl-software.de/members/patryk-gorol.64620/).

Please let me know if you have any more questions.
