### ISSUE TITLE
advanced customfield + woocommerce connector

### ISSUE THREAD

**Issue by tommy83** [jtl-software/connector-woocommerce3#14]
**The situation - out of the box**
The WooCommerce/JJTL Connecor already supports many default product fields and details out of the box.
But most of all plugins are still not supported and many information are still missing via API.

**Improvement** 
In order to improve the flexebility and to gain information/data per product, i recommend the integration of ACF - Advanced custom fields pro. This allows a lot of data to be added via API.

**Impact**
Thirdparty plugins, themebuilder and templates can access new/more data and gives a lot of more possibility.
For example you can show information from a customfield in product detail page which is important for this product.
You can show/hide information (customfield) per userrole or cart value.
You can have structured information in acf fields and not putting all information into attribute table.
Thirdparty plugins can not read attribute table, but they can read information from product acf customfield.

@Patrick-Gugelsberger i see a lot of forum posts in official JTL forum about that need. How we can help out or support you in this job?

All the best
Tommy

**Comment by Patrick-Gugelsberger** [comment]
Hey Tommy,

thanks for your suggestion. We've created a voting thread in our forums.

You can find the thread here:
https://forum.jtl-software.de/threads/evaluierung-advanced-custom-fields-plugin-unterstuetzen.210327/
