### ISSUE TITLE
Enhance Compatibility with New High-Performance Order Storage

### ISSUE THREAD

**Issue by stefpb** [jtl-software/connector-woocommerce3#15]
We recognize the significance of transitioning to the new High-Performance Order Storage system. Historically, WooCommerce employed a method of writing orders to the wp_posts database table and utilizing its postmeta. With the introduction of the High-Performance Order Storage, we have an opportunity to optimize our order management process.

References:

WooCommerce High-Performance Order Storage Progress Report: [Link](https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/)
High-Performance Order Storage Upgrade Recipe Book: [Link](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book)

Request:
We would like to explore the possibility of making our existing codebase compatible with the new custom_order_tables. This enhancement would not only help us take full advantage of the High-Performance Order Storage but also improve the overall efficiency of our order management system.

Any guidance, suggestions, or insights regarding this endeavor would be greatly appreciated. Thank you for your support in advancing our WooCommerce implementation.

![image](https://github.com/jtl-software/connector-woocommerce3/assets/1069441/954e2463-40cc-4add-a03d-cf354f1179a6)

**Comment by Platzke-jtl** [comment]
Yes we are aware and wokring on it https://issues.jtl-software.de/issues/CO-2377

**Comment by stefpb** [comment]
Thank you very much for the realization. Our shop is now significantly faster. Unfortunately, if we deactivate compatibility mode, payments will not be transferred. You can see in the screenshot from my initial post. "Keep the posts and orders tables in sync (compatibility mode)" => off. Can you solve this problem?

---

Danke schön für die Realisierung. Unser Shop ist nun deutlich schneller. Leider ist es nun so, dass wenn wir den Kompatibilitätsmodus deaktivieren, dass dann Zahlungen nicht mit übertragen werden. Sie sehen in dem Screenshot von meinen initialen Beitrag. "Keep the posts and orders tables in sync (compatiblity mode)" => aus. Können Sie dieses Problem lösen?

**Comment by stefpb** [comment]
I see you are using (the outdated order meta syntax) `get_post_meta($order_id, $meta_key, true)`, for hpos support you need to convert to `wc_get_order($order_id)->get_meta($meta_key, true)` when it is an order. For customer groups or products you can leave the code as is.

A [search for get_post](https://github.com/search?q=repo%3Ajtl-software%2Fconnector-woocommerce3%20get_post&type=code) identifies:
- https://github.com/jtl-software/connector-woocommerce3/blob/007922fa5f67bd444d0d538c1344a7b4b6b80abc/src/Controllers/CustomerOrderController.php#L139
- https://github.com/jtl-software/connector-woocommerce3/blob/007922fa5f67bd444d0d538c1344a7b4b6b80abc/src/Controllers/CustomerOrderController.php#L223
- https://github.com/jtl-software/connector-woocommerce3/blob/007922fa5f67bd444d0d538c1344a7b4b6b80abc/src/Utilities/Util.php#L208
- https://github.com/jtl-software/connector-woocommerce3/blob/007922fa5f67bd444d0d538c1344a7b4b6b80abc/src/Controllers/Order/CustomerOrderShippingAddressController.php#L51

I followed these instructions: https://webkul.com/blog/woocommerce-plugin-high-performance-order-storage-compatible/

I hope I could help a bit.
