### ISSUE TITLE
Plugins are not loaded

### ISSUE THREAD

**Issue by ALSGruppe-S-Georgi** [jtl-software/connector-woocommerce3#16]
Since the update to the current version (1.40.4), the connector plugins are no longer loaded. By rolling back to version 1.39.10 it works again.

**Comment by Platzke-jtl** [comment]
We updated from Connector Core 3 to Conenctor Core 5, Plugins for Core 3 are no longer supported as the Plugin API has changed.

**Comment by fooku18** [comment]
how is that not a breaking change?

**Comment by squareloop1** [comment]
I was hit by that update too. Custom Plugins are not working anymore. Documentation for migration is non existent and the documentation on creating custom plugins is also very thin and confusing. Its a total nightmare having to maintain a shop with a JTL connector.

**Comment by Kimmax** [comment]
bro
