### ISSUE TITLE
Change the way the VAT is calculated when more than one tax class in order

### ISSUE THREAD

**Issue by Hamsterkacke** [jtl-software/connector-woocommerce3#2]
Normal WooCommerce behaviour is rounding per line item, not at the subtotal level.

The connector instead doesn't use rounded values when there are more than one tax class per order.

https://github.com/jtl-software/connector-woocommerce3/blob/master/src/Controllers/Order/CustomerOrderItem.php#L112

This throws some problems when sending data to JTL, because the values are off. This can easily be fixed when switching both of the function cals to rounding (Last parameter to true) or have an if else statement to get the stored value from the WooCommerce Options:

get_option( 'woocommerce_tax_round_at_subtotal' );

There are a lot of issues on the woocommerce side about rounding is wrong etc. Often this occurs, when rounding is set to subtotal instead of line. But this is exactly what you are doing right now.

Maybe it is better to update this, to use rounded prices when you calculate the VAT Rate.

I hope this is enough info, if not, please ping me and i happily assist with more data or a pull request. :)

**Comment by drieschel** [comment]
Hello @Hamsterkacke,

thanks for the proposal. Our main WooCommerce Connector developer is in holidays. We will discuss this when he is back. 

Thank you.

**Comment by Hamsterkacke** [comment]
Hey @drieschel 

Looks like a immediate fix was already pushed into the codebase, that seems to solve this problem, right?
Unfortunately, i have found another issue regarding tax calculation. Will open a new Issue.

**Comment by paprykasz** [comment]
Hey @Hamsterkacke 

yes, we reverted changes that makes problem with vat calculations and it should work. We will try to improve this calculations in future.

**Comment by Hamsterkacke** [comment]
Added a PR that should also fix this issue. :)

**Comment by paprykasz** [comment]
Please see #3
