### ISSUE TITLE
VAT calculation with coupon that makes the whole order free

### ISSUE THREAD

**Issue by Hamsterkacke** [jtl-software/connector-woocommerce3#3]
Hey,

i found another problem with the manual vat calculation.

If an order has a coupon applied, that makes the whole order free, the JTL Connector tries to calculate the vat rate by itself, even in the case that the whole order has a single vat rate.

This will result in a vat rate of 0 transmitted to JTL and will mess up the order there.

Ideally, it still would transmit a vat of 19% (or whatever) and still have a net and gross price of 0€.

Best
Philipp

**Comment by paprykasz** [comment]
Hey @Hamsterkacke 

thanks for your feedback. I'll take a closer look on this soon, if you have idea how to improve it we are open to suggestions.

**Comment by Hamsterkacke** [comment]
Hey, thanks for the reply!

When i find the time today, i'll have a look how the whole taxing process could be improved in the connector when there are multiple rates and also a single rat but the order results in 0.

**Comment by Hamsterkacke** [comment]
I added a PR :)

**Comment by paprykasz** [comment]
Hey @Hamsterkacke 

thanks again for the proposal, we use your solution but with some modifications. 

Tax rates can change in future and this can lead to errors when you re import orders. We decided to add hook 'woocommerce_checkout_create_order_line_item' and store vat in order item meta fields. 
When we import order we can check if meta data for vat is there so we can use it directly. Please take a look [here](https://github.com/jtl-software/connector-woocommerce3/commit/be12907dccbc26a515384bf78ab14d6ae2429a47).

**Comment by paprykasz** [comment]
Vat calculation improvements were added in 1.12.0
