### ISSUE TITLE
PHP8 Compatible

### ISSUE THREAD

**Issue by stefpb** [jtl-software/connector-woocommerce3#8]
After an update of PHP to 8.0 we get this error:

![image](https://user-images.githubusercontent.com/1069441/122674965-aae15500-d1d7-11eb-9ceb-e6b07f62eff5.png)

Fehler beim Verbindungsaufbau: Exception bei global_data.pull: Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.

Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.

Response: <Empty>

**Comment by paprykasz** [comment]
Hey @stefpb,

Thank you for your feedback. New connector version was just released with refactoring in controllers to fix PHP8 compatibility problems. I cannot see details of error that you posted but I think new release should fix it.

Please let me know if you have any questions.

All The Best,
Patryk

**Comment by itsolon** [comment]
in the meantime php 8.0 compatibility is given.
the question i have is: is there a roadmap when you support php 8.1 some time?
